#pragma once
#include <string>

class Folders{

public:
	enum FolderType { HUD, LEVELS, BATTLE, DIALOGUE, MENU, INTERMISSION, ARENA };

	static const std::string ROOT_FOLDER, HUD_FOLDER, LEVELS_FOLDER, BATTLE_FOLDER, DIALOGUE_FOLDER, MUSIC_FOLDER, SOUNDS_FOLDER, MENU_FOLDER, ICON_FOLDER, LUA_MAINFOLDER, MAIN_JSON_LOADERFILE, WEAPON_FOLDER, USEABLE_FOLDER, INTERMISSION_FOLDER, ITEM_FOLDER, UNIT_FOLDER, CHAPTER_FOLDER, ARENA_FOLDER, LEVEL_DIALOGUEFOLDER, MAIN_SCENEFOLDER;
	static const std::string MAIN_BATTLESCENEFOLDER;
};